apiVersion: v1
kind: Service
metadata:
  name: {{ include "moment.fullname" . }}
  labels:
    {{- include "moment.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "moment.selector" . | nindent 4 }}
