// Generated by build_voice.py from narration.json. Do not edit.
window.TIMELINE = {
 "scenes": [
  {
   "id": "intro",
   "start": 0.0,
   "dur": 9.82,
   "cues": {
    "this": {
     "t": 2.6,
     "d": 0.928
    },
    "tag": {
     "t": 4.028,
     "d": 4.592
    }
   }
  },
  {
   "id": "problem",
   "start": 9.82,
   "dur": 13.197,
   "cues": {
    "scroll": {
     "t": 0.5,
     "d": 2.066
    },
    "rarer": {
     "t": 3.016,
     "d": 2.381
    },
    "dual": {
     "t": 5.946,
     "d": 4.258
    },
    "line": {
     "t": 10.654,
     "d": 1.644
    }
   }
  },
  {
   "id": "ritual",
   "start": 23.018,
   "dur": 20.961,
   "cues": {
    "wallet": {
     "t": 0.5,
     "d": 2.487
    },
    "stake": {
     "t": 3.687,
     "d": 4.928
    },
    "capture": {
     "t": 9.315,
     "d": 2.238
    },
    "publish": {
     "t": 13.153,
     "d": 1.533
    },
    "feed": {
     "t": 15.686,
     "d": 3.675
    }
   }
  },
  {
   "id": "decay",
   "start": 43.979,
   "dur": 18.027,
   "cues": {
    "round": {
     "t": 0.5,
     "d": 3.673
    },
    "miss": {
     "t": 4.673,
     "d": 3.125
    },
    "seq": {
     "t": 8.198,
     "d": 3.842
    },
    "month": {
     "t": 12.54,
     "d": 4.487
    }
   }
  },
  {
   "id": "pool",
   "start": 62.006,
   "dur": 18.103,
   "cues": {
    "fund": {
     "t": 0.4,
     "d": 1.832
    },
    "close": {
     "t": 2.732,
     "d": 7.418
    },
    "example": {
     "t": 10.75,
     "d": 5.753
    }
   }
  },
  {
   "id": "fair",
   "start": 80.109,
   "dur": 18.582,
   "cues": {
    "mint": {
     "t": 0.4,
     "d": 4.083
    },
    "forfeit": {
     "t": 4.883,
     "d": 3.531
    },
    "rollover": {
     "t": 8.915,
     "d": 3.139
    },
    "exit": {
     "t": 12.654,
     "d": 4.728
    }
   }
  },
  {
   "id": "skr",
   "start": 98.691,
   "dur": 13.092,
   "cues": {
    "utility": {
     "t": 0.4,
     "d": 2.417
    },
    "list": {
     "t": 3.117,
     "d": 8.574
    }
   }
  },
  {
   "id": "tech",
   "start": 111.782,
   "dur": 26.483,
   "cues": {
    "app": {
     "t": 0.4,
     "d": 3.041
    },
    "manifest": {
     "t": 3.941,
     "d": 6.544
    },
    "encrypt": {
     "t": 10.985,
     "d": 4.149
    },
    "moderation": {
     "t": 15.634,
     "d": 6.307
    },
    "trust": {
     "t": 22.44,
     "d": 2.842
    }
   }
  },
  {
   "id": "program",
   "start": 138.265,
   "dur": 16.591,
   "cues": {
    "accounts": {
     "t": 0.4,
     "d": 7.278
    },
    "crank": {
     "t": 8.178,
     "d": 7.412
    }
   }
  },
  {
   "id": "outro",
   "start": 154.856,
   "dur": 15.359,
   "cues": {
    "live": {
     "t": 0.4,
     "d": 6.051
    },
    "words": {
     "t": 7.051,
     "d": 1.72
    },
    "end": {
     "t": 9.571,
     "d": 1.588
    }
   }
  }
 ],
 "duration": 170.215
};
