"""Generate the narration with Kokoro TTS and derive the video timeline.

Outputs:
  composition/timeline.js   cue times read by the motion composition
  build/narration.wav       full voice track (24 kHz mono)
  moment-hackathon.srt      English captions
"""
import hashlib
import json
import os
import sys

import numpy as np
import soundfile as sf

HERE = os.path.dirname(os.path.abspath(__file__))
MODEL_DIR = os.environ.get("KOKORO_DIR", os.path.join(HERE, ".cache"))
BUILD = os.path.join(HERE, "build")
SR = 24_000


def trim(samples, threshold=0.004, pad=0.03):
    loud = np.where(np.abs(samples) > threshold)[0]
    if len(loud) == 0:
        return samples
    start = max(loud[0] - int(pad * SR), 0)
    end = min(loud[-1] + int(pad * SR), len(samples))
    return samples[start:end]


def srt_time(seconds):
    ms = int(round(seconds * 1000))
    h, ms = divmod(ms, 3_600_000)
    m, ms = divmod(ms, 60_000)
    s, ms = divmod(ms, 1000)
    return f"{h:02}:{m:02}:{s:02},{ms:03}"


def main():
    with open(os.path.join(HERE, "narration.json")) as f:
        script = json.load(f)
    os.makedirs(os.path.join(BUILD, "lines"), exist_ok=True)

    kokoro = None
    clips = {}
    for scene in script["scenes"]:
        for line in scene["lines"]:
            text = line.get("tts", line["text"])
            key = hashlib.sha1(f"{script['voice']}|{script['speed']}|{text}".encode()).hexdigest()[:16]
            path = os.path.join(BUILD, "lines", f"{scene['id']}-{line['id']}-{key}.wav")
            if not os.path.exists(path):
                if kokoro is None:
                    from kokoro_onnx import Kokoro
                    kokoro = Kokoro(os.path.join(MODEL_DIR, "kokoro.onnx"), os.path.join(MODEL_DIR, "voices.bin"))
                samples, sr = kokoro.create(text, voice=script["voice"], speed=script["speed"], lang="en-us")
                assert sr == SR
                sf.write(path, trim(samples), SR)
                print("tts", scene["id"], line["id"], file=sys.stderr)
            clips[(scene["id"], line["id"])], _ = sf.read(path, dtype="float32")

    timeline = {"scenes": [], "duration": 0.0}
    captions = []
    t = 0.0
    for scene in script["scenes"]:
        start = t
        cursor = start + scene.get("lead", 0.5)
        cues = {}
        for i, line in enumerate(scene["lines"]):
            dur = len(clips[(scene["id"], line["id"])]) / SR
            cues[line["id"]] = {"t": round(cursor - start, 3), "d": round(dur, 3)}
            captions.append((cursor, cursor + dur, line["text"], (scene["id"], line["id"])))
            cursor += dur
            if i < len(scene["lines"]) - 1:
                cursor += line.get("gap", script["defaultGap"])
        end = max(cursor + scene.get("tail", 0.8), start + scene.get("minDur", 0))
        timeline["scenes"].append({"id": scene["id"], "start": round(start, 3), "dur": round(end - start, 3), "cues": cues})
        t = end
    timeline["duration"] = round(t, 3)

    voice = np.zeros(int(np.ceil(t * SR)) + SR, dtype=np.float32)
    for start, _end, _text, key in captions:
        clip = clips[key]
        i = int(round(start * SR))
        voice[i:i + len(clip)] += clip
    sf.write(os.path.join(BUILD, "narration.wav"), voice, SR)

    with open(os.path.join(HERE, "composition", "timeline.js"), "w") as f:
        f.write("// Generated by build_voice.py from narration.json. Do not edit.\n")
        f.write("window.TIMELINE = " + json.dumps(timeline, indent=1) + ";\n")

    with open(os.path.join(HERE, "moment-hackathon.srt"), "w") as f:
        for n, (start, end, text, _key) in enumerate(captions, 1):
            f.write(f"{n}\n{srt_time(start)} --> {srt_time(end + 0.15)}\n{text}\n\n")

    for scene in timeline["scenes"]:
        print(f"{scene['id']:<8} start {scene['start']:7.2f}  dur {scene['dur']:6.2f}")
    print(f"total {t:.2f}s")


if __name__ == "__main__":
    main()
